version: '3.3'

services:
  whoami:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.whoami-https.rule=Host(`whoami.daosoftware.com.br`)
      - traefik.http.routers.whoami-https.entrypoints=https
      - traefik.http.routers.whoami-https.tls=true
      - traefik.http.routers.whoami-https.tls.certresolver=le
      - traefik.http.services.whoami-https.loadbalancer.server.port=80
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
