version: '3.8'

services:
  mysql:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./dumps/:/var/lib/postgresql/dumps
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: examplepassword
    networks:
      - database_backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  db_data:
    driver: local

networks:
  database_backend:
    driver: overlay
    attachable: true
