version: '3.8'

services:
  postgres:
    image: postgres:16.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dumps/:/var/lib/postgresql/dumps
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: postgres_password
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis:
    image: redis:latest
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  postgres_password:
    external: true
          
volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: overlay
    attachable: true
