
version: '3.8'

services:
  redis:
    image: redis:latest
    networks:
      - database_backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  database_backend:
    driver: overlay
    attachable: true
