version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: adminpassword
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: overlay
