version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: code
        target: /var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - traefik-public
      - database_backend
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # HTTPS Router
        - traefik.http.routers.${PROJECT_NAME}-https.rule=Host(`${DEV_URL}`)
        - traefik.http.routers.${PROJECT_NAME}-https.entrypoints=https
        - traefik.http.routers.${PROJECT_NAME}-https.tls=true
        - traefik.http.routers.${PROJECT_NAME}-https.tls.certresolver=le
        - traefik.http.services.${PROJECT_NAME}-https.loadbalancer.server.port=80
        # HTTP Router
        - traefik.http.routers.${PROJECT_NAME}-http.rule=Host(`${DEV_URL}`)
        - traefik.http.routers.${PROJECT_NAME}-http.entrypoints=http
        - traefik.http.routers.${PROJECT_NAME}-http.middlewares=https-redirect

volumes:
  code:
    external: true
    name: ${PROJECT_NAME}

networks:
  traefik-public:
    external: true
  database_backend:
    external: true