version: '3.8'

services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dumps/:/var/lib/postgresql/dumps
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: examplepassword
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  phpmyadmin:
    image: phpmyadmin
    networks:
      - database_backend
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # HTTPS Router
        - traefik.http.routers.conafarq-https.rule=Host(`conafarq.com.br`) || Host(`www.conafarq.com.br`)
        - traefik.http.routers.conafarq-https.entrypoints=https
        - traefik.http.routers.conafarq-https.tls=true
        - traefik.http.routers.conafarq-https.tls.certresolver=le
        - traefik.http.services.conafarq-https.loadbalancer.server.port=8000
        # HTTP Router
        - traefik.http.routers.conafarq-http.rule=Host(`conafarq.com.br`) || Host(`www.conafarq.com.br`)
        - traefik.http.routers.conafarq-http.entrypoints=http
        - traefik.http.routers.conafarq-http.middlewares=https-redirect


volumes:
  mysql_data:
    driver: local

networks:
  backend:
    driver: overlay
    attachable: true